### ISSUE TITLE
Todo 삭제 기능 작성

### ISSUE THREAD

**Issue by JulyK9** [JulyK9/pre-project-react-tutorial#2]
### 해당 기능 구현을 위해 할 일
1. [ ] 작성된 todo 각 목록에 삭제할 버튼 추가
2. [ ] 삭제 버튼 클릭시 작동될 함수 생성
3. [ ] 할일 데이터에서 해당 할일을 삭제할 로직 작성

### 예상 작업 시간
2시간
