### ISSUE TITLE
Todo 할일 완료 체크 기능 작성

### ISSUE THREAD

**Issue by JulyK9** [JulyK9/pre-project-react-tutorial#4]
### 해당 기능 구현을 위해 할 일
1. [ ] 체크(완료) 상태 표현을 위한 추가 상태 관리 설정
2. [ ] 할일 데이터의 완료 상태 관리를 위한 키값 추가 설정
3. [ ] 클릭시 전환을 실행할 버튼 설정
4. [ ] 클릭시 전환 로직을 구현할 함수 작성
5. [ ] 상태 전환에 따른 디자인 css 작성

### 예상 작업 시간
4시간
